version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 123456
    volumes:
      - data:/var/lib/postgresql/data

  app:
    build:
      context: . 
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - default
    links:
      - db
    ports:
      - 8080:8080
    environment:
      POSTGRES_CONNECTION_STRING: host=db port=5432 user=testuser dbname=productsdb password=123456 sslmode=disable

volumes:
  data: